server:
  port: ${PORT:8082}

spring:
  application:
    name: driver-vehicle-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DRIVER_DATABASE:ridelink_driver_db}
      auto-index-creation: true

services:
  account-service:
    url: ${ACCOUNT_SERVICE_URL:http://localhost:8081}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
