server:
  port: ${PORT:8083}

spring:
  application:
    name: ride-management-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_RIDE_DATABASE:ridelink_ride_db}
      auto-index-creation: true

services:
  driver-service:
    url: ${DRIVER_SERVICE_URL:http://localhost:8082}
  fare-service:
    url: ${FARE_SERVICE_URL:http://localhost:8084}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
