server:
  port: ${PORT:8081}

spring:
  application:
    name: account-service
  data:
    mongodb:
> main
      database: ${MONGODB_ACCOUNT_DATABASE:ridelink_account_db}
      auto-index-creation: 

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B59703273357638792F423F4528482B4D6251}
  expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
